title: Pavlo Lisovyi — lisovyi.net
description: >-
  Pavlo Lisovyi's personal site
url: "https://lisovyi.net"
email: pavlo@lisovyi.net

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme
remote_theme: jekyll/minima
minima:
  skin: auto

# Collections
collections:
  thoughts:
    output: true
    permalink: /thoughts/:slug/

# Defaults
defaults:
  - scope:
      path: ""
      type: "thoughts"
    values:
      layout: "post"

# Exclude from processing.
exclude:
  - vendor/
  - README.md
  - Gemfile
  - Gemfile.lock
  - .git/
  - .github/
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - .bundle/
