title: Pavlo Lisovyi — lisovyi.net
description: >-
  Pavlo Lisovyi's personal site
url: "https://lisovyi.net"
email: pavlo@lisovyi.net

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme
remote_theme: jekyll/minima
minima:
  skin: auto

# Exclude from processing.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
