github: [metadata]

exclude: [ CNAME, Gemfile, Gemfile.lock, package.json, package-lock.json, README.md, node_modules, .idea, src, tsconfig.json ]

theme:

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed

# For SEO tag plugin
twitter:
  username: plisovyi
  card: summary

social:
  name: Pavlo Lisovyi
  links:
    - https://twitter.com/plisovyi
    - https://www.facebook.com/plisovyi
    - https://www.linkedin.com/in/plisovyi/
    - https://github.com/plisovyi

# data for site
contact:
  social:
    github:
      url: https://github.com/plisovyi/lisovyi.net
    twitter:
      url: https://twitter.com/plisovyi
    facebook:
      url: https://facebook.com/plisovyi