title: Pavlo Lisovyi — lisovyi.net
description: >-
  Pavlo Lisovyi's personal site
url: "https://lisovyi.net"
email: pavlo@lisovyi.net

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme
remote_theme: jekyll/minima@v2.5.2
minima:
  social_links:
    github: plisovyi

# Exclude from processing.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .git/
  - .github/
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - .bundle/
